### ISSUE TITLE
List grf issues and bugfixes to be reflected here

### ISSUE THREAD

**Issue by halflearned** [rajkumarkarthik/mgrf-develop#2]
The following issues and bugfixes were solved in the `grf` repo after `mgrf` forked it. (Not yet a complete list)

+ [ ] [#362](https://github.com/grf-labs/grf/pull/362) Remove the purity condition on outcomes during splitting
+ [ ] [#331](https://github.com/grf-labs/grf/pull/335) Fix a bug in causal forest tuning where imbalance.penalty was being cast to a bool 
Note: imbalance.penalty is still called `lambda` in `mgrf`
+ [ ] [#329](https://github.com/grf-labs/grf/pull/329) Allow for a factor as a cluster variable
+ [ ] [#294](https://github.com/grf-labs/grf/pull/294) Fixing zero-index observations in get_tree
+ [ ] [#259](https://github.com/grf-labs/grf/pull/259) RandomSampler::draw now uses Fisher-Yates algorithm

In addition to the above, the following functionality is missing from `mgrf`:
+ [ ] Computing a debiased estimate of the MSE for oob predictions
This starts with PR [#184](https://github.com/grf-labs/grf/pull/184), but subsequent PRs have also implemented several important bugfixes
+ [ ] Instrumental forests have a dedicated splitting strategy
Implementation [here](https://github.com/grf-labs/grf/blob/master/core/src/splitting/InstrumentalSplittingRule.cpp) 
+ [ ] Computing the average treatment and partial effects
ATE: [here](https://github.com/grf-labs/grf/blob/master/r-package/grf/R/average_treatment_effect.R), APE: [here](https://github.com/grf-labs/grf/blob/master/r-package/grf/R/average_partial_effect.R)

**Comment by KipchumbaE** [comment]
I tried to install mgrf using the R link provided. I already installed ‘grf’ version 1.2.0 but does not include multivariate treatments. I get the following error:
Error in download.file(p, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://raw.github.com/rajkumarkartik/mgrf-develop/master/releases/grf_0.9.3.tar.gz'
